spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: thread

  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      generate-unique-name: false

springdoc:
  swagger-ui:
    path: /docs
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: "my"





















